name-template: "Release Notes for v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "✨ Features"
    labels:
      - "feat"
      - "feature"
  - title: "🐞 Bug Fixes"
    labels:
      - "bug"
  - title: "📄 Other Changes"
    labels:
      - "other"
      - "documentation"
change-template: "- {{body}}"                     # Use the PR body (description) as the message
no-changes-template: "No significant changes in this release."

template: |
  # 🚀 Release Notes for {{version}}

  ## ✨ Features
  {{#categories.Features}}
  {{#pullRequests}}
  {{#labels}}
  {{#is "feat"}}
  - {{body}} (#{{number}}) by @{{author}}
  {{/is}}
  {{/labels}}
  {{/pullRequests}}
  {{/categories.Features}}

  ## 🐞 Bug Fixes
  {{#categories.Bug Fixes}}
  {{#pullRequests}}
  {{#labels}}
  {{#is "bug"}}
  - {{body}} (#{{number}}) by @{{author}}
  {{/is}}
  {{/labels}}
  {{/pullRequests}}
  {{/categories.Bug Fixes}}

  ## 📄 Other Changes
  {{#categories.Other Changes}}
  {{#pullRequests}}
  {{#labels}}
  {{#is "other"}}
  - {{body}} (#{{number}}) by @{{author}}
  {{/is}}
  {{/labels}}
  {{/pullRequests}}
  {{/categories.Other Changes}}

  ## 🏅 Contributors
  {{#contributors}}
  - @{{username}}
  {{/contributors}}
