name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "✨ Features"
    labels:
      - feature
      - enhancement
      - new-feature
      - feat
  - title: "🐞 Bug Fixes"
    labels:
      - fix
      - bugfix
      - bug
      - defect
  - title: "📄 Other Changes"
    labels:
      - other
      - documentation
      - docs
  - title: "🔧 Maintenance"
    labels:
      - chore
      - refactor
      - maintenance

change-template: '- $TITLE by @$AUTHOR (#$NUMBER): $BODY'

version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - feature
      - feat
      - enhancement
  patch:
    labels:
      - patch
      - fix
      - bug
      - chore
      - maintenance
  default: patch

template: |
  🚀 Release Notes for $RESOLVED_VERSION

  ## ✨ Features
  {{#categories.Features}}
  {{#pullRequests}}
  {{#labels}}
  {{#is "feature"}}
  - $TITLE (#$NUMBER) by @$AUTHOR: $BODY
  {{/is}}
  {{/labels}}
  {{/pullRequests}}
  {{/categories.Features}}

  ## 🐞 Bug Fixes
  {{#categories.Bug Fixes}}
  {{#pullRequests}}
  {{#labels}}
  {{#is "bug"}}
  - $TITLE (#$NUMBER) by @$AUTHOR: $BODY
  {{/is}}
  {{/labels}}
  {{/pullRequests}}
  {{/categories.Bug Fixes}}

  ## 📄 Other Changes
  {{#categories.Other Changes}}
  {{#pullRequests}}
  {{#labels}}
  {{#is "other"}}
  - $TITLE (#$NUMBER) by @$AUTHOR: $BODY
  {{/is}}
  {{/labels}}
  {{/pullRequests}}
  {{/categories.Other Changes}}

  ## 🔧 Maintenance
  {{#categories.Maintenance}}
  {{#pullRequests}}
  {{#labels}}
  {{#is "maintenance"}}
  - $TITLE (#$NUMBER) by @$AUTHOR: $BODY
  {{/is}}
  {{/labels}}
  {{/pullRequests}}
  {{/categories.Maintenance}}

  ## 🏅 Contributors
  {{#contributors}}
  - @$USERNAME
  {{/contributors}}
