name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
      - new-feature
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bugfix
      - bug
      - defect
  - title: 🔧 Maintenance
    labels:
      - chore
      - refactor
      - maintenance
  - title: 📖 Documentation Updates
    labels:
      - documentation
      - docs
  - title: 🌟 Improvements
    labels:
      - improvement
      - optimization
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)': $BODY'
version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - feature
      - feat
      - enhancement
  patch:
    labels:
      - patch
      - fix
      - bug
      - chore
      - maintenance
  default: patch
template: |
  ## 🚀 Release Notes

  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
